# SPDX-FileCopyrightText: 2025 Hyperpolymath
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Palimpsest-0.5

name = "Docudactyl"
uuid = "a7e3f2d1-8c4b-4e5a-9f6d-2b3c4a5e6f7d"
authors = ["Hyperpolymath <hyperpolymath@proton.me>"]
version = "0.1.0"

[deps]
PDFIO = "4d0d745f-9d9a-5c48-8f81-b84e51d2c4f3"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.9"
PDFIO = "0.1"
DataFrames = "1.6"
CSV = "0.10"
JSON3 = "1.13"
ArgParse = "1.1"
